[project]
name = "task-tracker"
version = "0.1.0"
description = "A command line tool for task management."
readme = "README.md"
authors = [
    { name = "Richard Goshen", email = "rick.goshen@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
task-tracker = "task_tracker:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "ruff>=0.16.6",
]
